#!/usr/bin/env bash
# This `DEBIAN/postrm` script is run post-uninstallation

set -e

systemctl stop ghm-node                    || true
systemctl disable ghm-node                 || true
rm -f /etc/systemd/system/ghm-node.service || true
systemctl daemon-reload                       || true
