#!/usr/bin/env bash
# This `DEBIAN/postinst` script is run post-installation

set -e

if [[ -z "$SUDO_USER" ]]
then
    export SUDO_USER=root
fi

cat <<EOF > /etc/systemd/system/ghm-node.service
[Unit]
Description=HermitMatrixNetwork node service
After=network.target

[Service]
Type=simple
Environment=GHM_ENCLAVE_DIR=/usr/lib
WorkingDirectory=$(eval echo ~"$SUDO_USER")
ExecStart=/usr/local/bin/ghmd start
User=$SUDO_USER
Restart=on-failure
StartLimitInterval=0
RestartSec=3
LimitNOFILE=65535
LimitMEMLOCK=209715200

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

mkdir -p "/opt/ghm/.sgx_ghms"
chown -R "$SUDO_USER":"$SUDO_USER" "/opt/ghm/.sgx_ghms"
mkdir -p "/opt/ghm/.ghmd/.node"
mkdir -p "$(eval echo ~"$SUDO_USER")/.sgx_ghms"