version: '3'

services:
  bootstrap:
    image: enigmampc/secret-network-sw-dev-custom-bootstrap:latest
    container_name: bootstrap
    volumes:
#      - /tmp/ghmcli:/root/.ghmcli
      - /tmp/ghmd-bootstrap:/root/.ghmd
#      - /tmp/ghmdbootstrap:/root/.ghmd
      - /tmp/sgx_secrets:/opt/ghm/.sgx_ghms
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657
      - 1317
      - 1337
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 1337:1337

#  node:
#    image: enigmampc/secret-network-sw-dev-custom-node:latest
#    container_name: node
#    depends_on:
#      - bootstrap
#    volumes:
#      - /tmp/ghmd-bootstrap:/tmp/.ghmd
##      - /tmp/ghmdbootstrap:/tmp/.ghmd
#      - /tmp/ghmd-node:/root/.ghmd
#      - /tmp/ghmcli:/root/.ghmcli
##      - /tmp/sgx_secrets:/root/.sgx_secrets
#    stdin_open: true
#    tty: true
#    environment:
#      - http_proxy
#      - https_proxy
#    ports:
#      - 26657:26657
